# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modbus_visualizer.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1079, 581)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainFrame.sizePolicy().hasHeightForWidth())
        self.mainFrame.setSizePolicy(sizePolicy)
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.mainFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.networkConfigFrame = QtWidgets.QFrame(self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.networkConfigFrame.sizePolicy().hasHeightForWidth())
        self.networkConfigFrame.setSizePolicy(sizePolicy)
        self.networkConfigFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.networkConfigFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.networkConfigFrame.setObjectName("networkConfigFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.networkConfigFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tcpRadioButton = QtWidgets.QRadioButton(self.networkConfigFrame)
        self.tcpRadioButton.setObjectName("tcpRadioButton")
        self.gridLayout_2.addWidget(self.tcpRadioButton, 0, 1, 1, 1)
        self.rtuRadioButton = QtWidgets.QRadioButton(self.networkConfigFrame)
        self.rtuRadioButton.setObjectName("rtuRadioButton")
        self.gridLayout_2.addWidget(self.rtuRadioButton, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.networkConfigFrame, 0, 0, 1, 1)
        self.pollingSettingsGroupBox = QtWidgets.QGroupBox(self.mainFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pollingSettingsGroupBox.sizePolicy().hasHeightForWidth())
        self.pollingSettingsGroupBox.setSizePolicy(sizePolicy)
        self.pollingSettingsGroupBox.setObjectName("pollingSettingsGroupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.pollingSettingsGroupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.startRegisterSpinBox = QtWidgets.QSpinBox(self.pollingSettingsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startRegisterSpinBox.sizePolicy().hasHeightForWidth())
        self.startRegisterSpinBox.setSizePolicy(sizePolicy)
        self.startRegisterSpinBox.setProperty("value", 1)
        self.startRegisterSpinBox.setObjectName("startRegisterSpinBox")
        self.gridLayout_4.addWidget(self.startRegisterSpinBox, 1, 2, 1, 1)
        self.numberOfRegistersLabel = QtWidgets.QLabel(self.pollingSettingsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numberOfRegistersLabel.sizePolicy().hasHeightForWidth())
        self.numberOfRegistersLabel.setSizePolicy(sizePolicy)
        self.numberOfRegistersLabel.setObjectName("numberOfRegistersLabel")
        self.gridLayout_4.addWidget(self.numberOfRegistersLabel, 0, 4, 1, 1)
        self.registerTypeLabel = QtWidgets.QLabel(self.pollingSettingsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.registerTypeLabel.sizePolicy().hasHeightForWidth())
        self.registerTypeLabel.setSizePolicy(sizePolicy)
        self.registerTypeLabel.setObjectName("registerTypeLabel")
        self.gridLayout_4.addWidget(self.registerTypeLabel, 0, 0, 1, 1)
        self.numberOfRegistersSpinBox = QtWidgets.QSpinBox(self.pollingSettingsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numberOfRegistersSpinBox.sizePolicy().hasHeightForWidth())
        self.numberOfRegistersSpinBox.setSizePolicy(sizePolicy)
        self.numberOfRegistersSpinBox.setToolTip("")
        self.numberOfRegistersSpinBox.setMinimum(1)
        self.numberOfRegistersSpinBox.setMaximum(100)
        self.numberOfRegistersSpinBox.setObjectName("numberOfRegistersSpinBox")
        self.gridLayout_4.addWidget(self.numberOfRegistersSpinBox, 1, 4, 1, 1)
        self.startRegisterLabel = QtWidgets.QLabel(self.pollingSettingsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startRegisterLabel.sizePolicy().hasHeightForWidth())
        self.startRegisterLabel.setSizePolicy(sizePolicy)
        self.startRegisterLabel.setObjectName("startRegisterLabel")
        self.gridLayout_4.addWidget(self.startRegisterLabel, 0, 2, 1, 1)
        self.registerTypeComboBox = QtWidgets.QComboBox(self.pollingSettingsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.registerTypeComboBox.sizePolicy().hasHeightForWidth())
        self.registerTypeComboBox.setSizePolicy(sizePolicy)
        self.registerTypeComboBox.setObjectName("registerTypeComboBox")
        self.registerTypeComboBox.addItem("")
        self.registerTypeComboBox.addItem("")
        self.registerTypeComboBox.addItem("")
        self.registerTypeComboBox.addItem("")
        self.gridLayout_4.addWidget(self.registerTypeComboBox, 1, 0, 1, 1)
        self.updateTimeLabel = QtWidgets.QLabel(self.pollingSettingsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateTimeLabel.sizePolicy().hasHeightForWidth())
        self.updateTimeLabel.setSizePolicy(sizePolicy)
        self.updateTimeLabel.setObjectName("updateTimeLabel")
        self.gridLayout_4.addWidget(self.updateTimeLabel, 0, 6, 1, 1)
        self.updateTimeSpinBox = QtWidgets.QSpinBox(self.pollingSettingsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateTimeSpinBox.sizePolicy().hasHeightForWidth())
        self.updateTimeSpinBox.setSizePolicy(sizePolicy)
        self.updateTimeSpinBox.setMaximum(999999)
        self.updateTimeSpinBox.setObjectName("updateTimeSpinBox")
        self.gridLayout_4.addWidget(self.updateTimeSpinBox, 1, 6, 1, 1)
        self.singlePollPushButton = QtWidgets.QPushButton(self.pollingSettingsGroupBox)
        self.singlePollPushButton.setObjectName("singlePollPushButton")
        self.gridLayout_4.addWidget(self.singlePollPushButton, 2, 0, 1, 1)
        self.startPollingPushButton = QtWidgets.QPushButton(self.pollingSettingsGroupBox)
        self.startPollingPushButton.setObjectName("startPollingPushButton")
        self.gridLayout_4.addWidget(self.startPollingPushButton, 2, 2, 1, 1)
        self.gridLayout_3.addWidget(self.pollingSettingsGroupBox, 2, 0, 1, 1)
        self.pollTable = QtWidgets.QTableWidget(self.mainFrame)
        self.pollTable.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pollTable.sizePolicy().hasHeightForWidth())
        self.pollTable.setSizePolicy(sizePolicy)
        self.pollTable.setMinimumSize(QtCore.QSize(0, 0))
        self.pollTable.setMaximumSize(QtCore.QSize(1050, 350))
        self.pollTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.pollTable.setShowGrid(True)
        self.pollTable.setGridStyle(QtCore.Qt.SolidLine)
        self.pollTable.setColumnCount(10)
        self.pollTable.setObjectName("pollTable")
        self.pollTable.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.pollTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.pollTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.pollTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.pollTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.pollTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.pollTable.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.pollTable.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.pollTable.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.pollTable.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.pollTable.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.pollTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.pollTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.pollTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.pollTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.pollTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.pollTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.pollTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.pollTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.pollTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.pollTable.setHorizontalHeaderItem(9, item)
        self.pollTable.horizontalHeader().setVisible(True)
        self.pollTable.horizontalHeader().setCascadingSectionResizes(False)
        self.pollTable.verticalHeader().setSortIndicatorShown(False)
        self.pollTable.verticalHeader().setStretchLastSection(False)
        self.gridLayout_3.addWidget(self.pollTable, 3, 0, 1, 1)
        self.consoleLineEdit = QtWidgets.QLineEdit(self.mainFrame)
        self.consoleLineEdit.setEnabled(True)
        self.consoleLineEdit.setReadOnly(True)
        self.consoleLineEdit.setObjectName("consoleLineEdit")
        self.gridLayout_3.addWidget(self.consoleLineEdit, 4, 0, 1, 1)
        self.gridLayout.addWidget(self.mainFrame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1079, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tcpRadioButton.setText(_translate("MainWindow", "TCP"))
        self.rtuRadioButton.setText(_translate("MainWindow", "RTU"))
        self.pollingSettingsGroupBox.setTitle(_translate("MainWindow", "Polling Settings"))
        self.numberOfRegistersLabel.setText(_translate("MainWindow", "Number of Registers"))
        self.registerTypeLabel.setText(_translate("MainWindow", "Register Type"))
        self.startRegisterLabel.setText(_translate("MainWindow", "Start Register"))
        self.registerTypeComboBox.setItemText(0, _translate("MainWindow", "Coils"))
        self.registerTypeComboBox.setItemText(1, _translate("MainWindow", "Discrete Inputs"))
        self.registerTypeComboBox.setItemText(2, _translate("MainWindow", "Input Registers"))
        self.registerTypeComboBox.setItemText(3, _translate("MainWindow", "Holding Registers"))
        self.updateTimeLabel.setText(_translate("MainWindow", "Update Time"))
        self.singlePollPushButton.setText(_translate("MainWindow", "Single Poll"))
        self.startPollingPushButton.setText(_translate("MainWindow", "Start Polling"))
        self.pollTable.setSortingEnabled(False)
        item = self.pollTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "+0"))
        item = self.pollTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "+1"))
        item = self.pollTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "+2"))
        item = self.pollTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "+3"))
        item = self.pollTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "+4"))
        item = self.pollTable.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "+5"))
        item = self.pollTable.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "+6"))
        item = self.pollTable.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "+7"))
        item = self.pollTable.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "+8"))
        item = self.pollTable.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "+9"))
        item = self.pollTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.pollTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.pollTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.pollTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.pollTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.pollTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.pollTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.pollTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.pollTable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.pollTable.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

